classDiagram
    class Animal {
        +string name
        +int age
        +void eat()
        +void sleep()
    }

    class Dog {
        +String breed
        +void bark()
    }

    class Cat {
        +String color
        +void meow()
    }

    Animal <|-- Dog
    Animal <|-- Cat